static const char* onloads =
";;;\n"
";;; A few functions, including 'require', ship with the runtime, so that they're\n"
";;; always available. A script, format-onloads.ebl, will convert the file to a C\n"
";;; string literal, to be included by the VM during compilation.\n"
";;;\n"
"\n"
"(namespace std\n"
"  (defn some (pred lat)\n"
"    (if (null? lat)\n"
"        false\n"
"        (if (pred (car lat))\n"
"            (car lat)\n"
"            (recur pred (cdr lat))))))\n"
"\n"
"(def require\n"
"     ((lambda ()\n"
"        (def-mut required-set null)\n"
"        (lambda (file-name)\n"
"          (let ((found (std::some (lambda (n)\n"
"                                    (equal? n file-name)) required-set)))\n"
"            (if found\n"
"                null\n"
"                (begin\n"
"                  (load file-name)\n"
"                  (set required-set (cons file-name required-set)))))))))\n"
"\n"
"(defn list (...) ...)\n"
;